### ISSUE TITLE
 Not logged in: Timestamp too far from current time

### ISSUE THREAD

**Issue by mg64ve** [ftexchange/ftx#127]
Just got this error message today:

```
>>> from ftx import FtxClient
>>> import pandas as pd
>>> import json
>>> import re
>>> key = 'mykey'
>>> secret = 'mysecret'
>>> client = FtxClient(api_key=key, api_secret=secret)
>>> pos=client.get_positions()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/ftx/api.py", line 81, in wrapped
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ftx/api.py", line 284, in get_positions
    return self._get('positions', {'showAvgPrice': show_avg_price})
  File "/usr/local/lib/python3.9/site-packages/ftx/api.py", line 25, in _get
    return self._request('GET', path, params=params)
  File "/usr/local/lib/python3.9/site-packages/ftx/api.py", line 41, in _request
    return self._process_response(response)
  File "/usr/local/lib/python3.9/site-packages/ftx/api.py", line 68, in _process_response
    raise Exception(data['error'])
Exception: Not logged in: Timestamp too far from current time
```

I believe there is a change in FTX documentation:

> Authentication
> 
> For authenticated requests, the following headers should be sent with the request:
> 
>     FTX-KEY: Your API key
>     FTX-TS: Number of milliseconds since Unix epoch
>     FTX-SIGN: SHA256 HMAC of the following four strings, using your API secret, as a hex string:
>         Request timestamp (e.g. 1528394229375)
>         HTTP method in uppercase (e.g. GET or POST)
>         Request path, including leading slash and any URL parameters but not including the hostname (e.g. /account)
>         (POST only) Request body (JSON-encoded)
>     FTX-SUBACCOUNT (optional): URI-encoded name of the subaccount to use. Omit if not using subaccounts.
>

**Comment by mg64ve** [comment]
I think something in my server because I updated and rebooted and the problems is not there anymore.
